language: cpp
compiler: gcc
git:
  depth: false
notifications:
  email: false
branches:
  only:
    - master

env:
  CMAKE_GEN="Unix Makefiles"
  CMAKE_TCH_64="../src/cmake/toolchains/Linux-GNU-64.cmake"

install:
  - export CC="gcc-7" && export CXX="g++-7"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libmysql++3
      - libmysqlclient-dev
      
  coverity_scan:
    project:
      name: "Sphereserver/Source-experimental"
      description: "Game server for Ultima Online"
    notification_email: null@null
    branch_pattern: master
    build_command_prepend: cmake -G "$CMAKE_GEN" -DCMAKE_BUILD_TYPE="Nightly" -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TCH_64" ./src
    build_command: make -j4
      
script:
  - if [ $COVERITY_SCAN_BRANCH != 1 ]; then travis_terminate 0; fi
