image: Visual Studio 2017

# version format
version: 0.56.4.{build}

# branches to build
branches:
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

# Environmental variables
environment:
   MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
   CMAKE_GEN_32: Visual Studio 15 2017
   CMAKE_GEN_64: Visual Studio 15 2017 Win64
   BUILD_DIR_32: build-32
   BUILD_DIR_64: build-64

# to run your custom scripts instead of automatic MSBuild
build_script:
  - mkdir %BUILD_DIR_32% %BUILD_DIR_64%

  - ECHO ** Starting to build 64 bits Nightly
  - cd "%BUILD_DIR_64%"
  - cmake -G "%CMAKE_GEN_64%" ..\src
  - msbuild SphereServer.sln %MSBUILD_FLAGS% /p:Configuration=Nightly
  - ECHO ** Starting to build 64 bits Debug
  - msbuild SphereServer.sln %MSBUILD_FLAGS% /p:Configuration=Debug
  #/p:OutputPath="%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR_64%"

  - cd ..

  - ECHO ** Starting to build 32 bits Nightly
  - cd "%BUILD_DIR_32%"
  - cmake -G "%CMAKE_GEN_32%" ..\src
  - msbuild SphereServer.sln %MSBUILD_FLAGS% /p:Configuration=Nightly
  - ECHO ** Starting to build 32 bits Debug
  - msbuild SphereServer.sln %MSBUILD_FLAGS% /p:Configuration=Debug

  - cd ..

after_build:
  - ECHO ** Compilation done. Packing the files and uploading to FTP
  - mkdir accounts logs save scripts
  - 7z a SphereSvrX-Win64-Nightly.zip accounts\ logs\ save\ scripts\ "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR_64%\bin64\Nightly\SphereSvrX64_nightly.exe" "%APPVEYOR_BUILD_FOLDER%\src\sphere.ini" "%APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini"
  - 7z a SphereSvrX-Win64-Debug.zip accounts\ logs\ save\ scripts\ "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR_64%\bin64\Debug\SphereSvrX64_debug.exe" "%APPVEYOR_BUILD_FOLDER%\src\sphere.ini" "%APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini"
  - 7z a SphereSvrX-Win32-Nightly.zip accounts\ logs\ save\ scripts\ "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR_32%\bin\Nightly\SphereSvrX32_nightly.exe" "%APPVEYOR_BUILD_FOLDER%\src\sphere.ini" "%APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini"
  - 7z a SphereSvrX-Win32-Debug.zip accounts\ logs\ save\ scripts\ "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR_32%\bin\Debug\SphereSvrX32_debug.exe" "%APPVEYOR_BUILD_FOLDER%\src\sphere.ini" "%APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini"

#artifact: SphereSvrX-Win32-Nightly.zip SphereSvrX-Win64-Nightly.zip SphereSvrX-Win32-Debug.zip SphereSvrX-Win64-Debug.zip